### ISSUE TITLE
The scroll bar's stuck.

### ISSUE THREAD

**Issue by DanielYu8899** [rohanrhu/nodes.js#1]
I use it for part of my page, not the full page.  When the scroll bar scrolls to that part, it's stuck, then maybe 2s later, it shows.
I think this may be related to the performance of the animation，because this issue just occurs on some machines, but I don't know how to fix it.

Please help.

**Comment by rohanrhu** [comment]
Thank you for your feedback. I fixed something. (https://github.com/rohanrhu/nodes.js/commit/eca84e90a6485e77b0adaaf6025c553189ed636a)

You can try and give a feedback.
