### ISSUE TITLE
nodes' canvas dont fit page size after resize

### ISSUE THREAD

**Issue by unchair** [rohanrhu/nodes.js#4]
1. load web page with nodes.js canvas
2. resize page
3. see that region with particles smaller than web page

**Comment by rohanrhu** [comment]
Hi, you should follow window size.

```js
window.addEventListener('resize', function (event) {
    nodesjs.setHeight(window.height);
    nodesjs.setWidth(window.width);
});
```

**Comment by unchair** [comment]
> ```js
> window.addEventListener('resize', function (event) {
>     nodesjs.setHeight(window.height);
>     nodesjs.setWidth(window.width);
> });
> ```

not working, particles just disappearing on resize

**Comment by rohanrhu** [comment]
> > ```js
> > window.addEventListener('resize', function (event) {
> >     nodesjs.setHeight(window.height);
> >     nodesjs.setWidth(window.width);
> > });
> > ```
> 
> not working, particles just disappearing on resize

Can you send a screenshot?

**Comment by unchair** [comment]
> > > ```js
> > > window.addEventListener('resize', function (event) {
> > >     nodesjs.setHeight(window.height);
> > >     nodesjs.setWidth(window.width);
> > > });
> > > ```
> > 
> > 
> > not working, particles just disappearing on resize
> 
> Can you send a screenshot?

![image](https://user-images.githubusercontent.com/46081826/133480115-41c14da4-114c-494d-a7a4-0af337143a67.png)
![image](https://user-images.githubusercontent.com/46081826/133480139-859a7dc6-3a5c-4d1d-b2c0-587cba4d6840.png)

**Comment by rohanrhu** [comment]
Don't they walk over new empty area?

**Comment by rohanrhu** [comment]
If you want that all nodes to spread everywhere on resize, you can re-initialize the plugin on resize event.

**Comment by rohanrhu** [comment]
Or another way: make a big canvas and centralize it to screen (also re-centralize it on resize event). So with that big canvas, you should not resize it on resize event. If you don't apply these ways, nodes will slowly spread again to new empty space.
